### ISSUE TITLE
Develop a Helm chart for the Prefect API

### ISSUE THREAD

**Issue by zanieb** [PrefectHQ/prefect-intel#10]
Develop and publish a Helm chart for easy management of deployments of the Prefect API and associated services (scheduler, agents).

See [Prefect Server](https://github.com/PrefectHQ/server/tree/master/helm/prefect-server).

**Comment by gabcoyne** [comment]
Helm chart created for prefect orion API. New repo created to host prefect helm charts located at https://github.com/PrefectHQ/prefect-helm.
