### ISSUE TITLE
Determine SQLite compatibility with Windows

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect-intel#12]
The solution to this may be as simple as "always use conda" but want to make sure we at least track what our system requirements are as we discover them on Windows.

**Comment by madkinsz** [comment]
With conda it should always be fine since it installs SQLite for you. As part of this, we're interested in exploring what happens if you try to use Python outside of conda with Prefect.

**Comment by serinamarie** [comment]
Hi Michael, I requested your review on a PR that adds examples testing compatibility with Windows. 

With a Python 3.9 venv with dependencies installed from the requirements.txt, testing was done in a variety of scenarios:
1. Running flows with different task runners (SequentialTaskRunner, DaskTaskRunner, ConcurrentTaskRunner())
2. Storage creation (local and remote)
3. Deployments: SubprocessFlowRunner(), DockerFlowRunner(), UniversalFlowRunner()

Other notes:
storage, auth.toml, and config.toml were not in the /.prefect (although profiles.toml and orion.db were). I am wondering if they might be kept elsewhere on Windows, as the command `prefect config `view`` worked as expected. I don't believe there is a show-origin argument available at this time. But perhaps those could be useful for those who wanted to see their storage (deployment ids) and open their prefect config.

**Comment by madkinsz** [comment]
> With a Python 3.9 venv (not conda) with dependencies installed from the requirements.txt, testing was done in a variety of scenarios:

Great!

> auth.toml, and config.toml 

These are Prefect v1 files.
