### ISSUE TITLE
Add `main` branch CI to test installation of the `prefect` submodule

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect-intel#15]
This will ensure that the `main` branch is compatible with the `prefect` upstream it points to as well as provide test coverage for the conda environment specification.

We can likely include macOS and Windows runners, but at a minimum should include Linux.

**Comment by Sahiler** [comment]
Prefect installation is working within the Linux and MacOS runner - seen in the respective github [actions](https://github.com/PrefectHQ/prefect-intel/actions), testing with Windows runner still.

**Comment by Sahiler** [comment]
The different runners installing prefect are passing within the github action labeled "[Prefect Installation Test](https://github.com/PrefectHQ/prefect-intel/actions/workflows/prefect-installation-test.yml)"
