### ISSUE TITLE
Ensure paths are Windows compatibile

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect-intel#2]
All path objects used in Prefect should be compatible with Windows unless guaranteed to run on a POSIX compliant system.

**Comment by madkinsz** [comment]
Work in https://github.com/PrefectHQ/orion/pull/1792

**Comment by aregm** [comment]
> Work in https://github.com/PrefectHQ/orion/pull/1792

No access to the PR. Is it pushed to the beta?

**Comment by cicdw** [comment]
Yup an initial spec out of Windows compatibility was released with 2.0b4, and we're expecting a more thorough implementation that includes passing our test suite to go out with 2.0b5 this week
