### ISSUE TITLE
Add example using `RemoteFileSystem` and `S3FileSystem` with S3-compatible systems

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect-intel#41]
Requires #42

**Comment by serinamarie** [comment]
@madkinsz Do we need examples somewhere other than the README? Since prefect-aws is not part of the core, would we still expect to add it to the 2.0 docs?

**Comment by madkinsz** [comment]
I think an example in the `prefect-aws` docs would be sufficient for now.

**Comment by serinamarie** [comment]
Awesome, are we able to close this issue?

**Comment by zanieb** [comment]
:)
