### ISSUE TITLE
Add client-side flow run timeouts

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect-intel#7]
Add the ability to specify a timeout on a flow

```python
@flow(timeout_seconds=<float>)
```

After the timeout is expired, the client should propose a `FAILED` state for the flow run.

Note this timeout is detected and enforced by the client in this ticket.

**Comment by madkinsz** [comment]
This is already implemented as described above except the proposed state is `CRASHED`. We are considering changing this to `FAILED` and this ticket can be closed following that change (or denial of it). 

@billpalombi want to confirm or deny this behavioral change?

**Comment by billpalombi** [comment]
Yup this is consistent with what we discussed. Thank you!

**Comment by madkinsz** [comment]
I was mistaken and this is already a `FAILED`type state with a custom "TimedOut" name.
