### ISSUE TITLE
Publish Prefect 2.x to a conda repository

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect-intel#9]
Create a feedstock for conda-forge like https://github.com/conda-forge/prefect-feedstock to facilitate installation of Prefect via `conda`. This is especially useful for managing sqlite versions on older machines.

This may be challenging while the `beta` label is included in releases as conda-forge does not support alpha/beta tags.

**Comment by madkinsz** [comment]
We'll transition to a release candidate tag in July so we can accomplish this by August.

**Comment by mikeoconnor0308** [comment]
Any update on this - starting to try out prefect 2 in a conda heavy environment.

**Comment by Sahiler** [comment]
Currently working on this and will have the package ready shortly after GA is released next week.

**Comment by zanieb** [comment]
This is done :)
